version: '4'

networks:
  my_network:
    driver: bridge 

services:

  backend:
    container_name: rockschool_backend
    build:
      context: .
    ports:
      - "5000:8080"
    networks:
      - my_network
    depends_on:
      - "postgres"
    restart: on-failure

  postgres:
    image: postgres
    shm_size: '1gb'
    container_name: postgredb
    restart: always
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres:
    driver: local